Generating Data

you need to generate large matrices whose values have nothing to do with the
data one example of that is with neural networks a neural network is made up of many large matrices which you will
randomly initialize and then train using an algorithm called back propagation another common reason to create your own
arrays is to generate synthetic data to test your algorithm on often using synthetic data is extremely useful
because it allows us to test the efficiency of our models

In [3]:
import numpy as np

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
5*np.ones((2,3))

array([[5., 5., 5.],
       [5., 5., 5.]])

In [7]:
# numpy function to create identity matrix >>> eye
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.random.random() # in random all numbers would between 0 and 1

0.9076475127318312

In [9]:
np.random.random((2,3))# random matrix of size 2x3

array([[0.90304366, 0.72234697, 0.56910736],
       [0.68685516, 0.55284648, 0.02731886]])

In [11]:
#guassian
np.random.randn(2,3)

array([[ 0.45231709,  0.08032136, -1.93194602],
       [-0.67922138,  0.91934363,  0.52567758]])

In [13]:
R = np.random.randn(10000)

In [14]:
R

array([ 0.99457695,  0.94406747,  0.14135347, ..., -0.37289546,
       -0.68872986, -0.9062258 ])

In [15]:
R.mean()

0.002332752425129738

In [16]:
np.mean(R)

0.002332752425129738

In [17]:
 R.var()

0.9904182999525656

In [18]:
R.std()#sq.rt of variance

0.9951976185424509

In [19]:
np.cov(R)

array(0.99051735)