List vs array

a list looks like an array but it works more like a generic data structure
on the other hand an umpire array exists specifically to do math

In [37]:
import numpy as np
L = [1,2,3]

In [38]:
A = np.array([1,2,3])

In [39]:
for e in L:
    print(e)

1
2
3


In [40]:
for e in A:
    print(e)

1
2
3


In [41]:
L.append(4)

In [42]:
print(L)

[1, 2, 3, 4]


In [43]:
L+[5]

[1, 2, 3, 4, 5]

In [44]:
A+np.array([4])

array([5, 6, 7])

In [45]:
A+np.array([7])

array([ 8,  9, 10])

In [46]:
A+np.array([20])

array([21, 22, 23])

In [47]:
E= np.array((1,2,5,4))
arr1 = E + np.array(42)

print(arr1)


[43 44 47 46]


In [48]:
2*E

array([ 2,  4, 10,  8])

In [49]:
2* arr1

array([86, 88, 94, 92])

In [50]:
arr1 + arr1

array([86, 88, 94, 92])

In [51]:
L2 = []
for e in L:
    L2.append(e + 3)

In [52]:
L2

[4, 5, 6, 7]

In [53]:
L2 = [e + 3 for e in L]

In [54]:
L2

[4, 5, 6, 7]

In [55]:
L2 = []
for e in L:
    L2.append(e**2)

In [56]:
L2

[1, 4, 9, 16]

In [57]:
np.sqrt(L2)

array([1., 2., 3., 4.])

In [58]:
np.log(L2)

array([0.        , 1.38629436, 2.19722458, 2.77258872])

In [59]:
np.exp(L2)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [60]:
np.tanh(L2)

array([0.76159416, 0.9993293 , 0.99999997, 1.        ])

In [61]:
np.sinh(L2)

array([1.17520119e+00, 2.72899172e+01, 4.05154190e+03, 4.44305526e+06])

In [62]:
np.cosh(L2)

array([1.54308063e+00, 2.73082328e+01, 4.05154203e+03, 4.44305526e+06])